# Generated by Django 5.2.17 on 2026-10-09 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='file name')),
                ('dry_run', models.BooleanField(default=False, verbose_name='dry run')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('summary', models.JSONField(blank=True, default=dict, verbose_name='summary')),
            ],
            options={
                'verbose_name': 'import',
                'verbose_name_plural': 'imports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField(verbose_name='row')),
                ('raw', models.JSONField(verbose_name='raw data')),
                ('status', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('unchanged', 'Unchanged'), ('conflict', 'Conflict'), ('error', 'Error')], max_length=10, verbose_name='status')),
                ('messages', models.JSONField(blank=True, default=list, verbose_name='messages')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='importer.importbatch', verbose_name='import')),
                ('song', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_rows', to='catalog.song', verbose_name='song')),
            ],
            options={
                'verbose_name': 'import row',
                'verbose_name_plural': 'import rows',
                'ordering': ['batch', 'row_number'],
                'constraints': [models.UniqueConstraint(fields=('batch', 'row_number'), name='import_row_unique'), models.CheckConstraint(condition=models.Q(('status__in', ['created', 'updated', 'unchanged', 'conflict', 'error'])), name='import_row_status_valid')],
            },
        ),
    ]
