# Generated by Django 5.2.17 on 2026-10-06 10:26

import apps.catalog.models
import django.core.validators
import django.contrib.postgres.operations
import django.db.models.deletion
import django.db.models.functions.datetime
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # Used by song search (stage 4): fuzzy and accent-insensitive matching.
        django.contrib.postgres.operations.TrigramExtension(),
        django.contrib.postgres.operations.UnaccentExtension(),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='name')),
                ('iso_code', models.CharField(max_length=2, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{2}$', 'Two uppercase letters, ISO 3166-1 alpha-2.')], verbose_name='ISO code')),
            ],
            options={
                'verbose_name': 'country',
                'verbose_name_plural': 'countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=32, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('timezone', models.CharField(default='UTC', help_text='The daily puzzle changes at midnight in this time zone.', max_length=64, validators=[apps.catalog.models.validate_timezone], verbose_name='time zone')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'edition',
                'verbose_name_plural': 'editions',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=32, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'region',
                'verbose_name_plural': 'regions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='name')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='order')),
            ],
            options={
                'verbose_name': 'theme',
                'verbose_name_plural': 'themes',
                'ordering': ['group__order', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ThemeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='name')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='order')),
            ],
            options={
                'verbose_name': 'theme group',
                'verbose_name_plural': 'theme groups',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='name')),
                ('type', models.CharField(choices=[('solo', 'Solo'), ('group', 'Group'), ('duo', 'Duo'), ('collaboration', 'Collaboration')], max_length=16, verbose_name='type')),
                ('musicbrainz_id', models.UUIDField(blank=True, null=True, unique=True, verbose_name='MusicBrainz ID')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artists', to='catalog.country', verbose_name='country')),
            ],
            options={
                'verbose_name': 'artist',
                'verbose_name_plural': 'artists',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='name')),
                ('related', models.ManyToManyField(blank=True, help_text='A guess in a related genre gets a yellow tile.', to='catalog.genre', verbose_name='related genres')),
            ],
            options={
                'verbose_name': 'genre',
                'verbose_name_plural': 'genres',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='name')),
                ('iso_code', models.CharField(help_text='ISO 639-1 (en), or ISO 639-3 when there is no two-letter code (zxx = no lyrics).', max_length=3, unique=True, validators=[django.core.validators.RegexValidator('^[a-z]{2,3}$', 'Two or three lowercase letters.')], verbose_name='ISO code')),
            ],
            options={
                'verbose_name': 'language',
                'verbose_name_plural': 'languages',
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('iso_code__regex', '^[a-z]{2,3}$')), name='language_iso_code_format')],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='name')),
                ('musicbrainz_id', models.UUIDField(blank=True, null=True, unique=True, verbose_name='MusicBrainz ID')),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'people',
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('name__regex', '\\S')), name='person_name_not_blank')],
            },
        ),
        migrations.CreateModel(
            name='ArtistMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='catalog.artist', verbose_name='artist')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='catalog.person', verbose_name='person')),
            ],
            options={
                'verbose_name': 'artist member',
                'verbose_name_plural': 'artist members',
            },
        ),
        migrations.AddField(
            model_name='artist',
            name='members',
            field=models.ManyToManyField(related_name='artists', through='catalog.ArtistMember', to='catalog.person', verbose_name='members'),
        ),
        migrations.AddField(
            model_name='country',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='countries', to='catalog.region', verbose_name='region'),
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(help_text='Official title, without “(Remastered)”, “– Radio Edit” and the like.', max_length=200, verbose_name='title')),
                ('year', models.PositiveSmallIntegerField(blank=True, help_text='Year of the first official release (not a remaster or compilation).', null=True, validators=[django.core.validators.MinValueValidator(1900)], verbose_name='year')),
                ('vocal', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('mixed', 'Mixed'), ('instrumental', 'Instrumental')], max_length=16, verbose_name='vocal')),
                ('youtube_video_id', models.CharField(blank=True, help_text='Without it the game links to a YouTube search for “artist title”.', max_length=11, null=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9_-]{11}$', 'A YouTube video ID is exactly 11 characters: letters, digits, - or _.')], verbose_name='YouTube video ID')),
                ('musicbrainz_id', models.UUIDField(blank=True, null=True, unique=True, verbose_name='MusicBrainz ID')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=8, verbose_name='difficulty')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('verified', 'Verified')], default='draft', max_length=8, verbose_name='status')),
                ('sources', models.JSONField(blank=True, default=list, help_text='List of source URLs.', validators=[apps.catalog.models.validate_url_list], verbose_name='sources')),
                ('notes', models.TextField(blank=True, verbose_name='moderator notes')),
                ('editions', models.ManyToManyField(blank=True, related_name='songs', to='catalog.edition', verbose_name='editions')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='songs', to='catalog.genre', verbose_name='genre')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='songs', to='catalog.language', verbose_name='language')),
                ('primary_artist', models.ForeignKey(help_text='The artist credited on the original release. Featured artists go below.', on_delete=django.db.models.deletion.PROTECT, related_name='primary_songs', to='catalog.artist', verbose_name='primary artist')),
            ],
            options={
                'verbose_name': 'song',
                'verbose_name_plural': 'songs',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='In your own words. No lyric quotes. Must not mention the title or the artist.', verbose_name='text')),
                ('strength', models.CharField(choices=[('easy', 'Easy — subtle'), ('medium', 'Medium'), ('strong', 'Strong — revealing')], max_length=8, verbose_name='strength')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='order')),
                ('source_url', models.URLField(max_length=500, verbose_name='source URL')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='catalog.song', verbose_name='song')),
            ],
            options={
                'verbose_name': 'fact',
                'verbose_name_plural': 'facts',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='SongAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(help_text='Alternative spelling players may type, e.g. “Despasito”.', max_length=200, verbose_name='alias')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='catalog.song', verbose_name='song')),
            ],
            options={
                'verbose_name': 'alias',
                'verbose_name_plural': 'aliases',
                'ordering': ['alias'],
            },
        ),
        migrations.CreateModel(
            name='SongArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('primary', 'Primary'), ('featured', 'Featured')], default='featured', max_length=8, verbose_name='role')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='song_credits', to='catalog.artist', verbose_name='artist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_artists', to='catalog.song', verbose_name='song')),
            ],
            options={
                'verbose_name': 'song artist',
                'verbose_name_plural': 'song artists',
            },
        ),
        migrations.AddField(
            model_name='song',
            name='artists',
            field=models.ManyToManyField(related_name='songs', through='catalog.SongArtist', to='catalog.artist', verbose_name='artists'),
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='name')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='styles', to='catalog.genre', verbose_name='genre')),
            ],
            options={
                'verbose_name': 'style',
                'verbose_name_plural': 'styles',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='song',
            name='styles',
            field=models.ManyToManyField(blank=True, help_text='1–2 styles.', related_name='songs', to='catalog.style', verbose_name='styles'),
        ),
        migrations.CreateModel(
            name='SongTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, verbose_name='primary')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_themes', to='catalog.song', verbose_name='song')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='song_themes', to='catalog.theme', verbose_name='theme')),
            ],
            options={
                'verbose_name': 'song theme',
                'verbose_name_plural': 'song themes',
                'ordering': ['-is_primary', 'theme__name'],
            },
        ),
        migrations.AddField(
            model_name='song',
            name='themes',
            field=models.ManyToManyField(related_name='songs', through='catalog.SongTheme', to='catalog.theme', verbose_name='themes'),
        ),
        migrations.AddField(
            model_name='theme',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='themes', to='catalog.themegroup', verbose_name='group'),
        ),
        migrations.AddConstraint(
            model_name='artistmember',
            constraint=models.UniqueConstraint(fields=('artist', 'person'), name='artist_member_unique'),
        ),
        migrations.AddConstraint(
            model_name='artist',
            constraint=models.CheckConstraint(condition=models.Q(('name__regex', '\\S')), name='artist_name_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='artist',
            constraint=models.CheckConstraint(condition=models.Q(('type__in', ['solo', 'group', 'duo', 'collaboration'])), name='artist_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='country',
            constraint=models.CheckConstraint(condition=models.Q(('iso_code__regex', '^[A-Z]{2}$')), name='country_iso_code_format'),
        ),
        migrations.AddConstraint(
            model_name='fact',
            constraint=models.CheckConstraint(condition=models.Q(('text__regex', '\\S')), name='fact_text_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='fact',
            constraint=models.CheckConstraint(condition=models.Q(('source_url__regex', '\\S')), name='fact_source_url_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='fact',
            constraint=models.CheckConstraint(condition=models.Q(('strength__in', ['easy', 'medium', 'strong'])), name='fact_strength_valid'),
        ),
        migrations.AddConstraint(
            model_name='songalias',
            constraint=models.UniqueConstraint(models.F('song'), django.db.models.functions.text.Lower('alias'), name='song_alias_unique', violation_error_message='This song already has this alias.'),
        ),
        migrations.AddConstraint(
            model_name='songalias',
            constraint=models.CheckConstraint(condition=models.Q(('alias__regex', '\\S')), name='song_alias_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='songartist',
            constraint=models.UniqueConstraint(fields=('song', 'artist'), name='song_artist_unique'),
        ),
        migrations.AddConstraint(
            model_name='songartist',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'primary')), fields=('song',), name='song_artist_single_primary'),
        ),
        migrations.AddConstraint(
            model_name='songartist',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['primary', 'featured'])), name='song_artist_role_valid'),
        ),
        migrations.AddConstraint(
            model_name='songtheme',
            constraint=models.UniqueConstraint(fields=('song', 'theme'), name='song_theme_unique'),
        ),
        migrations.AddConstraint(
            model_name='songtheme',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('song',), name='song_theme_single_primary', violation_error_message='A song can have only one primary theme.'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['status', 'year'], name='song_status_year_idx'),
        ),
        migrations.AddConstraint(
            model_name='song',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), models.F('primary_artist'), name='song_unique_title_primary_artist', violation_error_message='This artist already has a song with this title.'),
        ),
        migrations.AddConstraint(
            model_name='song',
            constraint=models.CheckConstraint(condition=models.Q(('title__regex', '\\S')), name='song_title_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='song',
            constraint=models.CheckConstraint(condition=models.Q(('year__isnull', True), models.Q(('year__gte', 1900), ('year__lte', django.db.models.functions.datetime.ExtractYear(django.db.models.functions.datetime.Now()))), _connector='OR'), name='song_year_range', violation_error_message='The year must be between 1900 and the current year.'),
        ),
        migrations.AddConstraint(
            model_name='song',
            constraint=models.CheckConstraint(condition=models.Q(('youtube_video_id__isnull', True), ('youtube_video_id__regex', '^[A-Za-z0-9_-]{11}$'), _connector='OR'), name='song_youtube_video_id_format'),
        ),
        migrations.AddConstraint(
            model_name='song',
            constraint=models.CheckConstraint(condition=models.Q(('vocal__in', ['', 'male', 'female', 'mixed', 'instrumental'])), name='song_vocal_valid'),
        ),
        migrations.AddConstraint(
            model_name='song',
            constraint=models.CheckConstraint(condition=models.Q(('difficulty__in', ['easy', 'medium', 'hard'])), name='song_difficulty_valid'),
        ),
        migrations.AddConstraint(
            model_name='song',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'review', 'verified'])), name='song_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='song',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'verified'), _negated=True), models.Q(('genre__isnull', False), ('language__isnull', False), ('vocal__in', ['male', 'female', 'mixed', 'instrumental']), ('year__isnull', False)), _connector='OR'), name='song_verified_has_tile_fields', violation_error_message='A verified song needs a year, genre, vocal and language.'),
        ),
    ]
