# Generated by Django 5.2.17 on 2026-10-06 10:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPuzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('number', models.PositiveIntegerField(blank=True, help_text='Issue number. Leave empty to use the next free number.', verbose_name='number')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='puzzles', to='catalog.edition', verbose_name='edition')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='puzzles', to='catalog.song', verbose_name='song')),
            ],
            options={
                'verbose_name': 'daily puzzle',
                'verbose_name_plural': 'daily puzzles',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('player_token', models.UUIDField(help_text='Anonymous player ID from an httpOnly cookie.', verbose_name='player token')),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('won', 'Won'), ('lost', 'Lost'), ('gave_up', 'Gave up')], default='in_progress', max_length=16, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='finished at')),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='game.dailypuzzle', verbose_name='puzzle')),
            ],
            options={
                'verbose_name': 'game session',
                'verbose_name_plural': 'game sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Guess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveSmallIntegerField(verbose_name='attempt number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guesses', to='game.gamesession', verbose_name='session')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guesses', to='catalog.song', verbose_name='song')),
            ],
            options={
                'verbose_name': 'guess',
                'verbose_name_plural': 'guesses',
                'ordering': ['session', 'attempt_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='dailypuzzle',
            constraint=models.UniqueConstraint(fields=('edition', 'date'), name='puzzle_unique_edition_date', violation_error_message='This edition already has a puzzle on this date.'),
        ),
        migrations.AddConstraint(
            model_name='dailypuzzle',
            constraint=models.UniqueConstraint(fields=('edition', 'number'), name='puzzle_unique_edition_number', violation_error_message='This edition already has a puzzle with this number.'),
        ),
        migrations.AddConstraint(
            model_name='dailypuzzle',
            constraint=models.CheckConstraint(condition=models.Q(('number__gte', 1)), name='puzzle_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='gamesession',
            constraint=models.UniqueConstraint(fields=('player_token', 'puzzle'), name='session_unique_player_puzzle'),
        ),
        migrations.AddConstraint(
            model_name='gamesession',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['in_progress', 'won', 'lost', 'gave_up'])), name='session_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='gamesession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('finished_at__isnull', True), ('status', 'in_progress')), models.Q(models.Q(('status', 'in_progress'), _negated=True), ('finished_at__isnull', False)), _connector='OR'), name='session_finished_at_matches_status'),
        ),
        migrations.AddConstraint(
            model_name='guess',
            constraint=models.UniqueConstraint(fields=('session', 'attempt_number'), name='guess_unique_attempt'),
        ),
        migrations.AddConstraint(
            model_name='guess',
            constraint=models.UniqueConstraint(fields=('session', 'song'), name='guess_unique_song'),
        ),
        migrations.AddConstraint(
            model_name='guess',
            constraint=models.CheckConstraint(condition=models.Q(('attempt_number__gte', 1)), name='guess_attempt_positive'),
        ),
    ]
